// <auto-generated />
using System;
using CoffeeShops.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeeShops.DataAccess.Migrations
{
    [DbContext(typeof(CoffeeShopsContext))]
    [Migration("20251106133724_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeeShops.DataAccess.Models.CategoryDb", b =>
                {
                    b.Property<Guid>("Id_category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.HasKey("Id_category")
                        .HasName("id_category");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("CoffeeShops.DataAccess.Models.CoffeeShopDb", b =>
                {
                    b.Property<Guid>("Id_coffeeshop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_coffeeshop");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("address");

                    b.Property<Guid>("Id_company")
                        .HasColumnType("uuid")
                        .HasColumnName("id_company");

                    b.Property<string>("WorkingHours")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("workinghours");

                    b.HasKey("Id_coffeeshop")
                        .HasName("id_coffeeshop");

                    b.HasIndex("Id_company");

                    b.ToTable("coffeeshops", (string)null);
                });

            modelBuilder.Entity("CoffeeShops.DataAccess.Models.CompanyDb", b =>
                {
                    b.Property<Guid>("Id_company")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_company");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("website");

                    b.HasKey("Id_company")
                        .HasName("id_company");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("CoffeeShops.DataAccess.Models.DrinkDb", b =>
                {
                    b.Property<Guid>("Id_drink")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_drink");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.HasKey("Id_drink")
                        .HasName("id_drink");

                    b.ToTable("drinks", (string)null);
                });

            modelBuilder.Entity("CoffeeShops.DataAccess.Models.DrinksCategoryDb", b =>
                {
                    b.Property<Guid>("Id_drink")
                        .HasColumnType("uuid")
                        .HasColumnName("id_drink");

                    b.Property<Guid>("Id_category")
                        .HasColumnType("uuid")
                        .HasColumnName("id_category");

                    b.HasKey("Id_drink", "Id_category");

                    b.HasIndex("Id_category");

                    b.ToTable("drinkscategory", (string)null);
                });

            modelBuilder.Entity("CoffeeShops.DataAccess.Models.FavCoffeeShopsDb", b =>
                {
                    b.Property<Guid>("Id_user")
                        .HasColumnType("uuid")
                        .HasColumnName("id_user");

                    b.Property<Guid>("Id_coffeeshop")
                        .HasColumnType("uuid")
                        .HasColumnName("id_coffeeshop");

                    b.HasKey("Id_user", "Id_coffeeshop");

                    b.HasIndex("Id_coffeeshop");

                    b.ToTable("favcoffeeshops", (string)null);
                });

            modelBuilder.Entity("CoffeeShops.DataAccess.Models.FavDrinksDb", b =>
                {
                    b.Property<Guid>("Id_user")
                        .HasColumnType("uuid")
                        .HasColumnName("id_user");

                    b.Property<Guid>("Id_drink")
                        .HasColumnType("uuid")
                        .HasColumnName("id_drink");

                    b.HasKey("Id_user", "Id_drink");

                    b.HasIndex("Id_drink");

                    b.ToTable("favdrinks", (string)null);
                });

            modelBuilder.Entity("CoffeeShops.DataAccess.Models.MenuDb", b =>
                {
                    b.Property<Guid>("Id_drink")
                        .HasColumnType("uuid")
                        .HasColumnName("id_drink");

                    b.Property<Guid>("Id_company")
                        .HasColumnType("uuid")
                        .HasColumnName("id_company");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<int>("Size")
                        .HasColumnType("int")
                        .HasColumnName("size");

                    b.HasKey("Id_drink", "Id_company");

                    b.HasIndex("Id_company");

                    b.ToTable("menu", (string)null);
                });

            modelBuilder.Entity("CoffeeShops.DataAccess.Models.RoleDb", b =>
                {
                    b.Property<int>("Id_role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_role");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_role"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.HasKey("Id_role")
                        .HasName("id_role");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("CoffeeShops.DataAccess.Models.UserDb", b =>
                {
                    b.Property<Guid>("Id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_user");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birthdate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<int>("Id_role")
                        .HasColumnType("int")
                        .HasColumnName("id_role");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("password");

                    b.HasKey("Id_user")
                        .HasName("id_user");

                    b.HasIndex("Id_role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CoffeeShops.DataAccess.Models.CoffeeShopDb", b =>
                {
                    b.HasOne("CoffeeShops.DataAccess.Models.CompanyDb", "Company")
                        .WithMany("CoffeeShops")
                        .HasForeignKey("Id_company")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CoffeeShops.DataAccess.Models.DrinksCategoryDb", b =>
                {
                    b.HasOne("CoffeeShops.DataAccess.Models.CategoryDb", "Category")
                        .WithMany("DrinksCategory")
                        .HasForeignKey("Id_category")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeShops.DataAccess.Models.DrinkDb", "Drink")
                        .WithMany("DrinksCategory")
                        .HasForeignKey("Id_drink")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Drink");
                });

            modelBuilder.Entity("CoffeeShops.DataAccess.Models.FavCoffeeShopsDb", b =>
                {
                    b.HasOne("CoffeeShops.DataAccess.Models.CoffeeShopDb", "CoffeeShop")
                        .WithMany("FavCoffeeShops")
                        .HasForeignKey("Id_coffeeshop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeShops.DataAccess.Models.UserDb", "User")
                        .WithMany("FavCoffeeShops")
                        .HasForeignKey("Id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoffeeShop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoffeeShops.DataAccess.Models.FavDrinksDb", b =>
                {
                    b.HasOne("CoffeeShops.DataAccess.Models.DrinkDb", "Drink")
                        .WithMany("FavDrinks")
                        .HasForeignKey("Id_drink")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeShops.DataAccess.Models.UserDb", "User")
                        .WithMany("FavDrinks")
                        .HasForeignKey("Id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drink");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoffeeShops.DataAccess.Models.MenuDb", b =>
                {
                    b.HasOne("CoffeeShops.DataAccess.Models.CompanyDb", "Company")
                        .WithMany("Menu")
                        .HasForeignKey("Id_company")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeShops.DataAccess.Models.DrinkDb", "Drink")
                        .WithMany("Menu")
                        .HasForeignKey("Id_drink")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Drink");
                });

            modelBuilder.Entity("CoffeeShops.DataAccess.Models.UserDb", b =>
                {
                    b.HasOne("CoffeeShops.DataAccess.Models.RoleDb", "Role")
                        .WithMany("Users")
                        .HasForeignKey("Id_role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CoffeeShops.DataAccess.Models.CategoryDb", b =>
                {
                    b.Navigation("DrinksCategory");
                });

            modelBuilder.Entity("CoffeeShops.DataAccess.Models.CoffeeShopDb", b =>
                {
                    b.Navigation("FavCoffeeShops");
                });

            modelBuilder.Entity("CoffeeShops.DataAccess.Models.CompanyDb", b =>
                {
                    b.Navigation("CoffeeShops");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("CoffeeShops.DataAccess.Models.DrinkDb", b =>
                {
                    b.Navigation("DrinksCategory");

                    b.Navigation("FavDrinks");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("CoffeeShops.DataAccess.Models.RoleDb", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CoffeeShops.DataAccess.Models.UserDb", b =>
                {
                    b.Navigation("FavCoffeeShops");

                    b.Navigation("FavDrinks");
                });
#pragma warning restore 612, 618
        }
    }
}
