FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY *.sln .
COPY CoffeeShops.DataService/*.csproj CoffeeShops.DataService/
COPY CoffeeShops.DataAccess/*.csproj CoffeeShops.DataAccess/
COPY CoffeeShops.Domain/*.csproj CoffeeShops.Domain/
COPY CoffeeShops.DTOs/*.csproj CoffeeShops.DTOs/

# restore only the data-service project to avoid needing other solutions' csproj
RUN dotnet restore CoffeeShops.DataService/CoffeeShops.DataService.csproj

COPY . .

WORKDIR /src/CoffeeShops.DataService
RUN dotnet publish -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "CoffeeShops.DataService.dll"]
